edition = "2021"

condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
reorder_impl_items = true
reorder_modules = true
wrap_comments = true

group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Module"
newline_style = "Unix"
