[package]
name = "bevy_tui"
version = "0.9.1"
edition = "2021"
description = "A plugin for making interactive Bevy applications with a TUI instead of a graphical interface."
categories = []
keywords = ["bevy", "console", "terminal", "tui"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/sstelfox/bevy_tui"

[dependencies]
bevy = { default-features = false, version = "^0.9" }
crossterm = { version = "^0.25", features = [] }
tui = "^0.19"

[[example]]
name = "basic_ui"
path = "examples/basic_ui.rs"

[workspace]
resolver = "2"
members = [
  "tools/*",
]
